import 'package:flutter/services.dart';

/// Utilities for bidirectional text isolation, base direction detection,
/// and mixed-script handling in editors (SIRATI-27).
///
/// Follows Unicode Bidirectional Algorithm (UAX #9) standards.
class BidiTextUtils {
  BidiTextUtils._();

  /// Unicode Directional Formatting Characters
  static const lrm = '\u200E'; // Left-to-Right Mark
  static const rlm = '\u200F'; // Right-to-Left Mark
  static const lri = '\u2066'; // Left-to-Right Isolate
  static const rli = '\u2067'; // Right-to-Left Isolate
  static const pdi = '\u2069'; // Pop Directional Isolate
  static const lre = '\u202A'; // Left-to-Right Embedding
  static const pdf = '\u202C'; // Pop Directional Formatting

  // Regex identifying strong Arabic / Hebrew RTL script characters
  static final RegExp _rtlCharRegex = RegExp(
    r'[\u0590-\u05FF\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF\uFB50-\uFDFF\uFE70-\uFEFF]',
  );

  // Regex identifying strong Latin / Western LTR script characters
  static final RegExp _ltrCharRegex = RegExp(r'[A-Za-z]');

  // Common LTR token patterns that appear inside Arabic CV prose:
  // email, URL, phone numbers, tech acronyms, slash-separated paths/terms
  static final RegExp _embeddedLtrPattern = RegExp(
    r'((?:https?://|www\.)[^\s]+|[\w.+-]+@[\w-]+\.[\w.-]+|\+?[0-9][0-9\s-]{6,}[0-9]|[A-Za-z0-9+#./-]+(?:\s+[A-Za-z0-9+#./-]+)*)',
  );

  /// Detects the base paragraph direction based on the first strong directional character (UAX #9).
  ///
  /// Returns [TextDirection.rtl] if the first strong character is Arabic/RTL,
  /// [TextDirection.ltr] if it is Latin/LTR, or [fallback] if neutral/empty.
  static TextDirection detectBaseDirection(
    String? text, {
    TextDirection fallback = TextDirection.rtl,
  }) {
    if (text == null || text.isEmpty) return fallback;

    for (int i = 0; i < text.length; i++) {
      final char = text[i];
      if (_rtlCharRegex.hasMatch(char)) {
        return TextDirection.rtl;
      }
      if (_ltrCharRegex.hasMatch(char)) {
        return TextDirection.ltr;
      }
    }
    return fallback;
  }

  /// Wraps an LTR run in Left-to-Right Isolate (`\u2066` ... `\u2069`)
  /// so it does not scramble surrounding Arabic text or punctuation.
  static String isolateLtr(String text) {
    if (text.isEmpty) return text;
    return '$lri$text$pdi';
  }

  /// Wraps an RTL run in Right-to-Left Isolate (`\u2067` ... `\u2069`).
  static String isolateRtl(String text) {
    if (text.isEmpty) return text;
    return '$rli$text$pdi';
  }

  /// Isolates embedded technical terms, emails, URLs, and phone numbers inside
  /// an Arabic string using directional isolation markers.
  static String isolateEmbeddedLtrInArabic(String text) {
    if (text.isEmpty) return text;

    return text.replaceAllMapped(_embeddedLtrPattern, (match) {
      final matchedText = match.group(0) ?? '';
      // Only isolate if it contains Latin letters, URL schemes, or phone format
      if (_ltrCharRegex.hasMatch(matchedText) ||
          matchedText.contains('@') ||
          matchedText.contains('http') ||
          matchedText.startsWith('+')) {
        return '$lri$matchedText$pdi';
      }
      return matchedText;
    });
  }

  /// Strips dangling unclosed directional control characters to ensure
  /// clean logical storage in the database and JSON.
  static String sanitizeBidiControls(String text) {
    if (text.isEmpty) return text;
    return text.replaceAll(
        RegExp(r'[\u200E\u200F\u202A-\u202E\u2066-\u2069]'), '');
  }

  /// Normalizes Arabic presentation forms into canonical logical Unicode code points.
  /// Decomposes all forms in Presentation Forms-A (FB50..FDFF) and Forms-B (FE70..FEFF).
  static String toLogicalUnicode(String text) {
    if (text.isEmpty) return text;

    final buffer = StringBuffer();
    for (int i = 0; i < text.length; i++) {
      final code = text.codeUnitAt(i);
      final mapped = _presentationFormsMap[code];
      if (mapped != null) {
        buffer.write(mapped);
      } else {
        buffer.write(text[i]);
      }
    }
    return buffer.toString();
  }

  static const Map<int, String> _presentationFormsMap = {
    0xFB50: "ٱ",
    0xFB51: "ٱ",
    0xFB52: "ٻ",
    0xFB53: "ٻ",
    0xFB54: "ٻ",
    0xFB55: "ٻ",
    0xFB56: "پ",
    0xFB57: "پ",
    0xFB58: "پ",
    0xFB59: "پ",
    0xFB5A: "ڀ",
    0xFB5B: "ڀ",
    0xFB5C: "ڀ",
    0xFB5D: "ڀ",
    0xFB5E: "ٺ",
    0xFB5F: "ٺ",
    0xFB60: "ٺ",
    0xFB61: "ٺ",
    0xFB62: "ٿ",
    0xFB63: "ٿ",
    0xFB64: "ٿ",
    0xFB65: "ٿ",
    0xFB66: "ٹ",
    0xFB67: "ٹ",
    0xFB68: "ٹ",
    0xFB69: "ٹ",
    0xFB6A: "ڤ",
    0xFB6B: "ڤ",
    0xFB6C: "ڤ",
    0xFB6D: "ڤ",
    0xFB6E: "ڦ",
    0xFB6F: "ڦ",
    0xFB70: "ڦ",
    0xFB71: "ڦ",
    0xFB72: "ڄ",
    0xFB73: "ڄ",
    0xFB74: "ڄ",
    0xFB75: "ڄ",
    0xFB76: "ڃ",
    0xFB77: "ڃ",
    0xFB78: "ڃ",
    0xFB79: "ڃ",
    0xFB7A: "چ",
    0xFB7B: "چ",
    0xFB7C: "چ",
    0xFB7D: "چ",
    0xFB7E: "ڇ",
    0xFB7F: "ڇ",
    0xFB80: "ڇ",
    0xFB81: "ڇ",
    0xFB82: "ڍ",
    0xFB83: "ڍ",
    0xFB84: "ڌ",
    0xFB85: "ڌ",
    0xFB86: "ڎ",
    0xFB87: "ڎ",
    0xFB88: "ڈ",
    0xFB89: "ڈ",
    0xFB8A: "ژ",
    0xFB8B: "ژ",
    0xFB8C: "ڑ",
    0xFB8D: "ڑ",
    0xFB8E: "ک",
    0xFB8F: "ک",
    0xFB90: "ک",
    0xFB91: "ک",
    0xFB92: "گ",
    0xFB93: "گ",
    0xFB94: "گ",
    0xFB95: "گ",
    0xFB96: "ڳ",
    0xFB97: "ڳ",
    0xFB98: "ڳ",
    0xFB99: "ڳ",
    0xFB9A: "ڱ",
    0xFB9B: "ڱ",
    0xFB9C: "ڱ",
    0xFB9D: "ڱ",
    0xFB9E: "ں",
    0xFB9F: "ں",
    0xFBA0: "ڻ",
    0xFBA1: "ڻ",
    0xFBA2: "ڻ",
    0xFBA3: "ڻ",
    0xFBA4: "ۀ",
    0xFBA5: "ۀ",
    0xFBA6: "ہ",
    0xFBA7: "ہ",
    0xFBA8: "ہ",
    0xFBA9: "ہ",
    0xFBAA: "ھ",
    0xFBAB: "ھ",
    0xFBAC: "ھ",
    0xFBAD: "ھ",
    0xFBAE: "ے",
    0xFBAF: "ے",
    0xFBB0: "ۓ",
    0xFBB1: "ۓ",
    0xFBD3: "ڭ",
    0xFBD4: "ڭ",
    0xFBD5: "ڭ",
    0xFBD6: "ڭ",
    0xFBD7: "ۇ",
    0xFBD8: "ۇ",
    0xFBD9: "ۆ",
    0xFBDA: "ۆ",
    0xFBDB: "ۈ",
    0xFBDC: "ۈ",
    0xFBDD: "ۇٴ",
    0xFBDE: "ۋ",
    0xFBDF: "ۋ",
    0xFBE0: "ۅ",
    0xFBE1: "ۅ",
    0xFBE2: "ۉ",
    0xFBE3: "ۉ",
    0xFBE4: "ې",
    0xFBE5: "ې",
    0xFBE6: "ې",
    0xFBE7: "ې",
    0xFBE8: "ى",
    0xFBE9: "ى",
    0xFBEA: "ئا",
    0xFBEB: "ئا",
    0xFBEC: "ئە",
    0xFBED: "ئە",
    0xFBEE: "ئو",
    0xFBEF: "ئو",
    0xFBF0: "ئۇ",
    0xFBF1: "ئۇ",
    0xFBF2: "ئۆ",
    0xFBF3: "ئۆ",
    0xFBF4: "ئۈ",
    0xFBF5: "ئۈ",
    0xFBF6: "ئې",
    0xFBF7: "ئې",
    0xFBF8: "ئې",
    0xFBF9: "ئى",
    0xFBFA: "ئى",
    0xFBFB: "ئى",
    0xFBFC: "ی",
    0xFBFD: "ی",
    0xFBFE: "ی",
    0xFBFF: "ی",
    0xFC00: "ئج",
    0xFC01: "ئح",
    0xFC02: "ئم",
    0xFC03: "ئى",
    0xFC04: "ئي",
    0xFC05: "بج",
    0xFC06: "بح",
    0xFC07: "بخ",
    0xFC08: "بم",
    0xFC09: "بى",
    0xFC0A: "بي",
    0xFC0B: "تج",
    0xFC0C: "تح",
    0xFC0D: "تخ",
    0xFC0E: "تم",
    0xFC0F: "تى",
    0xFC10: "تي",
    0xFC11: "ثج",
    0xFC12: "ثم",
    0xFC13: "ثى",
    0xFC14: "ثي",
    0xFC15: "جح",
    0xFC16: "جم",
    0xFC17: "حج",
    0xFC18: "حم",
    0xFC19: "خج",
    0xFC1A: "خح",
    0xFC1B: "خم",
    0xFC1C: "سج",
    0xFC1D: "سح",
    0xFC1E: "سخ",
    0xFC1F: "سم",
    0xFC20: "صح",
    0xFC21: "صم",
    0xFC22: "ضج",
    0xFC23: "ضح",
    0xFC24: "ضخ",
    0xFC25: "ضم",
    0xFC26: "طح",
    0xFC27: "طم",
    0xFC28: "ظم",
    0xFC29: "عج",
    0xFC2A: "عم",
    0xFC2B: "غج",
    0xFC2C: "غم",
    0xFC2D: "فج",
    0xFC2E: "فح",
    0xFC2F: "فخ",
    0xFC30: "فم",
    0xFC31: "فى",
    0xFC32: "في",
    0xFC33: "قح",
    0xFC34: "قم",
    0xFC35: "قى",
    0xFC36: "قي",
    0xFC37: "كا",
    0xFC38: "كج",
    0xFC39: "كح",
    0xFC3A: "كخ",
    0xFC3B: "كل",
    0xFC3C: "كم",
    0xFC3D: "كى",
    0xFC3E: "كي",
    0xFC3F: "لج",
    0xFC40: "لح",
    0xFC41: "لخ",
    0xFC42: "لم",
    0xFC43: "لى",
    0xFC44: "لي",
    0xFC45: "مج",
    0xFC46: "مح",
    0xFC47: "مخ",
    0xFC48: "مم",
    0xFC49: "مى",
    0xFC4A: "مي",
    0xFC4B: "نج",
    0xFC4C: "نح",
    0xFC4D: "نخ",
    0xFC4E: "نم",
    0xFC4F: "نى",
    0xFC50: "ني",
    0xFC51: "هج",
    0xFC52: "هم",
    0xFC53: "هى",
    0xFC54: "هي",
    0xFC55: "يج",
    0xFC56: "يح",
    0xFC57: "يخ",
    0xFC58: "يم",
    0xFC59: "يى",
    0xFC5A: "يي",
    0xFC5B: "ذٰ",
    0xFC5C: "رٰ",
    0xFC5D: "ىٰ",
    0xFC5E: " ٌّ",
    0xFC5F: " ٍّ",
    0xFC60: " َّ",
    0xFC61: " ُّ",
    0xFC62: " ِّ",
    0xFC63: " ّٰ",
    0xFC64: "ئر",
    0xFC65: "ئز",
    0xFC66: "ئم",
    0xFC67: "ئن",
    0xFC68: "ئى",
    0xFC69: "ئي",
    0xFC6A: "بر",
    0xFC6B: "بز",
    0xFC6C: "بم",
    0xFC6D: "بن",
    0xFC6E: "بى",
    0xFC6F: "بي",
    0xFC70: "تر",
    0xFC71: "تز",
    0xFC72: "تم",
    0xFC73: "تن",
    0xFC74: "تى",
    0xFC75: "تي",
    0xFC76: "ثر",
    0xFC77: "ثز",
    0xFC78: "ثم",
    0xFC79: "ثن",
    0xFC7A: "ثى",
    0xFC7B: "ثي",
    0xFC7C: "فى",
    0xFC7D: "في",
    0xFC7E: "قى",
    0xFC7F: "قي",
    0xFC80: "كا",
    0xFC81: "كل",
    0xFC82: "كم",
    0xFC83: "كى",
    0xFC84: "كي",
    0xFC85: "لم",
    0xFC86: "لى",
    0xFC87: "لي",
    0xFC88: "ما",
    0xFC89: "مم",
    0xFC8A: "نر",
    0xFC8B: "نز",
    0xFC8C: "نم",
    0xFC8D: "نن",
    0xFC8E: "نى",
    0xFC8F: "ني",
    0xFC90: "ىٰ",
    0xFC91: "ير",
    0xFC92: "يز",
    0xFC93: "يم",
    0xFC94: "ين",
    0xFC95: "يى",
    0xFC96: "يي",
    0xFC97: "ئج",
    0xFC98: "ئح",
    0xFC99: "ئخ",
    0xFC9A: "ئم",
    0xFC9B: "ئه",
    0xFC9C: "بج",
    0xFC9D: "بح",
    0xFC9E: "بخ",
    0xFC9F: "بم",
    0xFCA0: "به",
    0xFCA1: "تج",
    0xFCA2: "تح",
    0xFCA3: "تخ",
    0xFCA4: "تم",
    0xFCA5: "ته",
    0xFCA6: "ثم",
    0xFCA7: "جح",
    0xFCA8: "جم",
    0xFCA9: "حج",
    0xFCAA: "حم",
    0xFCAB: "خج",
    0xFCAC: "خم",
    0xFCAD: "سج",
    0xFCAE: "سح",
    0xFCAF: "سخ",
    0xFCB0: "سم",
    0xFCB1: "صح",
    0xFCB2: "صخ",
    0xFCB3: "صم",
    0xFCB4: "ضج",
    0xFCB5: "ضح",
    0xFCB6: "ضخ",
    0xFCB7: "ضم",
    0xFCB8: "طح",
    0xFCB9: "ظم",
    0xFCBA: "عج",
    0xFCBB: "عم",
    0xFCBC: "غج",
    0xFCBD: "غم",
    0xFCBE: "فج",
    0xFCBF: "فح",
    0xFCC0: "فخ",
    0xFCC1: "فم",
    0xFCC2: "قح",
    0xFCC3: "قم",
    0xFCC4: "كج",
    0xFCC5: "كح",
    0xFCC6: "كخ",
    0xFCC7: "كل",
    0xFCC8: "كم",
    0xFCC9: "لج",
    0xFCCA: "لح",
    0xFCCB: "لخ",
    0xFCCC: "لم",
    0xFCCD: "له",
    0xFCCE: "مج",
    0xFCCF: "مح",
    0xFCD0: "مخ",
    0xFCD1: "مم",
    0xFCD2: "نج",
    0xFCD3: "نح",
    0xFCD4: "نخ",
    0xFCD5: "نم",
    0xFCD6: "نه",
    0xFCD7: "هج",
    0xFCD8: "هم",
    0xFCD9: "هٰ",
    0xFCDA: "يج",
    0xFCDB: "يح",
    0xFCDC: "يخ",
    0xFCDD: "يم",
    0xFCDE: "يه",
    0xFCDF: "ئم",
    0xFCE0: "ئه",
    0xFCE1: "بم",
    0xFCE2: "به",
    0xFCE3: "تم",
    0xFCE4: "ته",
    0xFCE5: "ثم",
    0xFCE6: "ثه",
    0xFCE7: "سم",
    0xFCE8: "سه",
    0xFCE9: "شم",
    0xFCEA: "شه",
    0xFCEB: "كل",
    0xFCEC: "كم",
    0xFCED: "لم",
    0xFCEE: "نم",
    0xFCEF: "نه",
    0xFCF0: "يم",
    0xFCF1: "يه",
    0xFCF2: "ـَّ",
    0xFCF3: "ـُّ",
    0xFCF4: "ـِّ",
    0xFCF5: "طى",
    0xFCF6: "طي",
    0xFCF7: "عى",
    0xFCF8: "عي",
    0xFCF9: "غى",
    0xFCFA: "غي",
    0xFCFB: "سى",
    0xFCFC: "سي",
    0xFCFD: "شى",
    0xFCFE: "شي",
    0xFCFF: "حى",
    0xFD00: "حي",
    0xFD01: "جى",
    0xFD02: "جي",
    0xFD03: "خى",
    0xFD04: "خي",
    0xFD05: "صى",
    0xFD06: "صي",
    0xFD07: "ضى",
    0xFD08: "ضي",
    0xFD09: "شج",
    0xFD0A: "شح",
    0xFD0B: "شخ",
    0xFD0C: "شم",
    0xFD0D: "شر",
    0xFD0E: "سر",
    0xFD0F: "صر",
    0xFD10: "ضر",
    0xFD11: "طى",
    0xFD12: "طي",
    0xFD13: "عى",
    0xFD14: "عي",
    0xFD15: "غى",
    0xFD16: "غي",
    0xFD17: "سى",
    0xFD18: "سي",
    0xFD19: "شى",
    0xFD1A: "شي",
    0xFD1B: "حى",
    0xFD1C: "حي",
    0xFD1D: "جى",
    0xFD1E: "جي",
    0xFD1F: "خى",
    0xFD20: "خي",
    0xFD21: "صى",
    0xFD22: "صي",
    0xFD23: "ضى",
    0xFD24: "ضي",
    0xFD25: "شج",
    0xFD26: "شح",
    0xFD27: "شخ",
    0xFD28: "شم",
    0xFD29: "شر",
    0xFD2A: "سر",
    0xFD2B: "صر",
    0xFD2C: "ضر",
    0xFD2D: "شج",
    0xFD2E: "شح",
    0xFD2F: "شخ",
    0xFD30: "شم",
    0xFD31: "سه",
    0xFD32: "شه",
    0xFD33: "طم",
    0xFD34: "سج",
    0xFD35: "سح",
    0xFD36: "سخ",
    0xFD37: "شج",
    0xFD38: "شح",
    0xFD39: "شخ",
    0xFD3A: "طم",
    0xFD3B: "ظم",
    0xFD3C: "اً",
    0xFD3D: "اً",
    0xFD50: "تجم",
    0xFD51: "تحج",
    0xFD52: "تحج",
    0xFD53: "تحم",
    0xFD54: "تخم",
    0xFD55: "تمج",
    0xFD56: "تمح",
    0xFD57: "تمخ",
    0xFD58: "جمح",
    0xFD59: "جمح",
    0xFD5A: "حمي",
    0xFD5B: "حمى",
    0xFD5C: "سحج",
    0xFD5D: "سجح",
    0xFD5E: "سجى",
    0xFD5F: "سمح",
    0xFD60: "سمح",
    0xFD61: "سمج",
    0xFD62: "سمم",
    0xFD63: "سمم",
    0xFD64: "صحح",
    0xFD65: "صحح",
    0xFD66: "صمم",
    0xFD67: "شحم",
    0xFD68: "شحم",
    0xFD69: "شجي",
    0xFD6A: "شمخ",
    0xFD6B: "شمخ",
    0xFD6C: "شمم",
    0xFD6D: "شمم",
    0xFD6E: "ضحى",
    0xFD6F: "ضخم",
    0xFD70: "ضخم",
    0xFD71: "طمح",
    0xFD72: "طمح",
    0xFD73: "طمم",
    0xFD74: "طمي",
    0xFD75: "عجم",
    0xFD76: "عمم",
    0xFD77: "عمم",
    0xFD78: "عمى",
    0xFD79: "غمم",
    0xFD7A: "غمي",
    0xFD7B: "غمى",
    0xFD7C: "فخم",
    0xFD7D: "فخم",
    0xFD7E: "قمح",
    0xFD7F: "قمم",
    0xFD80: "لحم",
    0xFD81: "لحي",
    0xFD82: "لحى",
    0xFD83: "لجج",
    0xFD84: "لجج",
    0xFD85: "لخم",
    0xFD86: "لخم",
    0xFD87: "لمح",
    0xFD88: "لمح",
    0xFD89: "محج",
    0xFD8A: "محم",
    0xFD8B: "محي",
    0xFD8C: "مجح",
    0xFD8D: "مجم",
    0xFD8E: "مخج",
    0xFD8F: "مخم",
    0xFD92: "مجخ",
    0xFD93: "همج",
    0xFD94: "همم",
    0xFD95: "نحم",
    0xFD96: "نحى",
    0xFD97: "نجم",
    0xFD98: "نجم",
    0xFD99: "نجى",
    0xFD9A: "نمي",
    0xFD9B: "نمى",
    0xFD9C: "يمم",
    0xFD9D: "يمم",
    0xFD9E: "بخي",
    0xFD9F: "تجي",
    0xFDA0: "تجى",
    0xFDA1: "تخي",
    0xFDA2: "تخى",
    0xFDA3: "تمي",
    0xFDA4: "تمى",
    0xFDA5: "جمي",
    0xFDA6: "جحى",
    0xFDA7: "جمى",
    0xFDA8: "سخى",
    0xFDA9: "صحي",
    0xFDAA: "شحي",
    0xFDAB: "ضحي",
    0xFDAC: "لجي",
    0xFDAD: "لمي",
    0xFDAE: "يحي",
    0xFDAF: "يجي",
    0xFDB0: "يمي",
    0xFDB1: "ممي",
    0xFDB2: "قمي",
    0xFDB3: "نحي",
    0xFDB4: "قمح",
    0xFDB5: "لحم",
    0xFDB6: "عمي",
    0xFDB7: "كمي",
    0xFDB8: "نجح",
    0xFDB9: "مخي",
    0xFDBA: "لجم",
    0xFDBB: "كمم",
    0xFDBC: "لجم",
    0xFDBD: "نجح",
    0xFDBE: "جحي",
    0xFDBF: "حجي",
    0xFDC0: "مجي",
    0xFDC1: "فمي",
    0xFDC2: "بحي",
    0xFDC3: "كمم",
    0xFDC4: "عجم",
    0xFDC5: "صمم",
    0xFDC6: "سخي",
    0xFDC7: "نجي",
    0xFDF0: "صلے",
    0xFDF1: "قلے",
    0xFDF2: "الله",
    0xFDF3: "اكبر",
    0xFDF4: "محمد",
    0xFDF5: "صلعم",
    0xFDF6: "رسول",
    0xFDF7: "عليه",
    0xFDF8: "وسلم",
    0xFDF9: "صلى",
    0xFDFA: "صلى الله عليه وسلم",
    0xFDFB: "جل جلاله",
    0xFDFC: "ریال",
    0xFE70: "ً",
    0xFE71: "ـً",
    0xFE72: "ٌ",
    0xFE74: "ٍ",
    0xFE76: " َ",
    0xFE77: "ـَ",
    0xFE78: " ُ",
    0xFE79: "ـُ",
    0xFE7A: " ِ",
    0xFE7B: "ـِ",
    0xFE7C: " ّ",
    0xFE7D: "ـّ",
    0xFE7E: " ْ",
    0xFE7F: "ـْ",
    0xFE80: "ء",
    0xFE81: "آ",
    0xFE82: "آ",
    0xFE83: "أ",
    0xFE84: "أ",
    0xFE85: "ؤ",
    0xFE86: "ؤ",
    0xFE87: "إ",
    0xFE88: "إ",
    0xFE89: "ئ",
    0xFE8A: "ئ",
    0xFE8B: "ئ",
    0xFE8C: "ئ",
    0xFE8D: "ا",
    0xFE8E: "ا",
    0xFE8F: "ب",
    0xFE90: "ب",
    0xFE91: "ب",
    0xFE92: "ب",
    0xFE93: "ة",
    0xFE94: "ة",
    0xFE95: "ت",
    0xFE96: "ت",
    0xFE97: "ت",
    0xFE98: "ت",
    0xFE99: "ث",
    0xFE9A: "ث",
    0xFE9B: "ث",
    0xFE9C: "ث",
    0xFE9D: "ج",
    0xFE9E: "ج",
    0xFE9F: "ج",
    0xFEA0: "ج",
    0xFEA1: "ح",
    0xFEA2: "ح",
    0xFEA3: "ح",
    0xFEA4: "ح",
    0xFEA5: "خ",
    0xFEA6: "خ",
    0xFEA7: "خ",
    0xFEA8: "خ",
    0xFEA9: "د",
    0xFEAA: "د",
    0xFEAB: "ذ",
    0xFEAC: "ذ",
    0xFEAD: "ر",
    0xFEAE: "ر",
    0xFEAF: "ز",
    0xFEB0: "ز",
    0xFEB1: "س",
    0xFEB2: "س",
    0xFEB3: "س",
    0xFEB4: "س",
    0xFEB5: "ش",
    0xFEB6: "ش",
    0xFEB7: "ش",
    0xFEB8: "ش",
    0xFEB9: "ص",
    0xFEBA: "ص",
    0xFEBB: "ص",
    0xFEBC: "ص",
    0xFEBD: "ض",
    0xFEBE: "ض",
    0xFEBF: "ض",
    0xFEC0: "ض",
    0xFEC1: "ط",
    0xFEC2: "ط",
    0xFEC3: "ط",
    0xFEC4: "ط",
    0xFEC5: "ظ",
    0xFEC6: "ظ",
    0xFEC7: "ظ",
    0xFEC8: "ظ",
    0xFEC9: "ع",
    0xFECA: "ع",
    0xFECB: "ع",
    0xFECC: "ع",
    0xFECD: "غ",
    0xFECE: "غ",
    0xFECF: "غ",
    0xFED0: "غ",
    0xFED1: "ف",
    0xFED2: "ف",
    0xFED3: "ف",
    0xFED4: "ف",
    0xFED5: "ق",
    0xFED6: "ق",
    0xFED7: "ق",
    0xFED8: "ق",
    0xFED9: "ك",
    0xFEDA: "ك",
    0xFEDB: "ك",
    0xFEDC: "ك",
    0xFEDD: "ل",
    0xFEDE: "ل",
    0xFEDF: "ل",
    0xFEE0: "ل",
    0xFEE1: "م",
    0xFEE2: "م",
    0xFEE3: "م",
    0xFEE4: "م",
    0xFEE5: "ن",
    0xFEE6: "ن",
    0xFEE7: "ن",
    0xFEE8: "ن",
    0xFEE9: "ه",
    0xFEEA: "ه",
    0xFEEB: "ه",
    0xFEEC: "ه",
    0xFEED: "و",
    0xFEEE: "و",
    0xFEEF: "ى",
    0xFEF0: "ى",
    0xFEF1: "ي",
    0xFEF2: "ي",
    0xFEF3: "ي",
    0xFEF4: "ي",
    0xFEF5: "لآ",
    0xFEF6: "لآ",
    0xFEF7: "لأ",
    0xFEF8: "لأ",
    0xFEF9: "لإ",
    0xFEFA: "لإ",
    0xFEFB: "لا",
    0xFEFC: "لا",
  };
}

/// Text input formatter that ensures clean logical Unicode is preserved
/// and prevents cursor glitches in mixed-direction text inputs.
class LogicalBidiInputFormatter extends TextInputFormatter {
  const LogicalBidiInputFormatter();

  @override
  TextEditingValue formatEditUpdate(
    TextEditingValue oldValue,
    TextEditingValue newValue,
  ) {
    final text = newValue.text;
    if (text.isEmpty) return newValue;

    // Fast check if any character needs decomposition
    bool hasPresentationForms = false;
    for (int i = 0; i < text.length; i++) {
      final code = text.codeUnitAt(i);
      if ((code >= 0xFB50 && code <= 0xFDFF) ||
          (code >= 0xFE70 && code <= 0xFEFF)) {
        hasPresentationForms = true;
        break;
      }
    }

    if (!hasPresentationForms) {
      return newValue;
    }

    final buffer = StringBuffer();
    final offsetMap = List<int>.filled(text.length + 1, 0);

    for (int i = 0; i < text.length; i++) {
      offsetMap[i] = buffer.length;
      final code = text.codeUnitAt(i);
      final mapped = BidiTextUtils._presentationFormsMap[code];
      if (mapped != null) {
        buffer.write(mapped);
      } else {
        buffer.write(text[i]);
      }
    }
    offsetMap[text.length] = buffer.length;

    final normalized = buffer.toString();

    int mapOffset(int rawOffset) {
      if (rawOffset < 0) return rawOffset;
      if (rawOffset >= offsetMap.length) return normalized.length;
      return offsetMap[rawOffset];
    }

    final newBase = mapOffset(newValue.selection.baseOffset);
    final newExtent = mapOffset(newValue.selection.extentOffset);
    final newSelection = newValue.selection.copyWith(
      baseOffset: newBase,
      extentOffset: newExtent,
    );

    TextRange newComposing = TextRange.empty;
    if (newValue.composing.isValid && !newValue.composing.isCollapsed) {
      final compStart = mapOffset(newValue.composing.start);
      final compEnd = mapOffset(newValue.composing.end);
      newComposing = TextRange(start: compStart, end: compEnd);
    }

    return TextEditingValue(
      text: normalized,
      selection: newSelection,
      composing: newComposing,
    );
  }
}
